### ISSUE TITLE
Somehow connection is dying and does not reconnect RabbitMQ.

### ISSUE THREAD

**Issue by b-erdem** [wso2-extensions/siddhi-io-rabbitmq#40] opened 2018-11-09 06:54 UTC
**Description:**
When I start product-sp with rabbitmq source connection it becomes broken after a few hours. And Product SP seems happy with it. We can't know if connection with rabbitmq is broken and it cannot reconnect to rabbitMQ. Any suggestion? Why this happens or how to prevent this to be happen?

**Affected Product Version:**
Product-SP Version: 4.1.0
siddhi-io-rabbitmq Version: 1.0.14

**Steps to reproduce:**

I can't specify steps to reproduce this issue but this occurs after a few hours when product-sp starts.

**Comment by niveathika** [comment] 2018-11-19 09:38
@b-erdem, Could you give more details on the above issue as I am unclear on the issue.
Is it, The SP is not recovering from a connection lost to rabbitMq OR the events consuming comes to a pause after few hours?

**Comment by filthz** [comment] 2019-08-27 08:51
I encountered a simmilar issue - the SP is not recovering from a connection lost to rabbitmq.

**Comment by filthz** [comment] 2019-08-27 10:43
could be a duplicate of https://github.com/siddhi-io/siddhi-io-rabbitmq/issues/46

**Comment by niveathika** [comment] 2019-08-27 11:17
@filthz Yes, it seems so, the fix is available on [v3.0.0](https://github.com/siddhi-io/siddhi-io-rabbitmq/releases/tag/v3.0.0) for Siddhi 5.x.x compatible version and [v1.1.2](https://github.com/siddhi-io/siddhi-io-rabbitmq/releases/tag/v1.1.2) for siddhi 4.3.x compatible version

**Closed as completed** 2019-08-27 11:18 UTC
